apiVersion: apps/v1
kind: Deployment
metadata:
  name: flog-deployment-production
  namespace: flog
  labels:
    app: flog-app-production
spec:
  selector:
    matchLabels:
      app: flog-app-production
  replicas: 2
  template:
    metadata:
      labels:
        app: flog-app-production
    spec:
      restartPolicy: Always
      containers:
        - name: flog-production
          image: gcr.io/flogmasters/flog_server:production
          imagePullPolicy: Always
          command: ['sh', '-c', 'echo xxx && sleep 6000']
          resources:
            limits:
              cpu: 1
              memory: 256Mi
            requests:
              cpu: 1
              memory: 256Mi
          ports:
            - containerPort: 8080
          env:
            - name: ACTIVE
              value: production
            - name: user_timezone
              value: Asia/Seoul
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flog-db
                  key: password
          readinessProbe:
            httpGet:
              path: /health_check.html
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep","2"]
      terminationGracePeriodSeconds: 60